### ISSUE TITLE
record sensor readings with seconds count and save to file

### ISSUE THREAD

**Issue by stumash** [stumash/MyCompassApp#1]
We need a way to diagnose what kind of phone movement causes bluriness in recorded images.  So, we'll record all sorts of sensor data to determine the orientation and movement of the phone at every point in time, and save all that to a csv to be analysed locally.

TLDR: record android sensor+orientation+movement data to .csv file

**Comment by IsaacBerman** [comment]
Started development on [recordSensorReadings_1](/stumash/MyCompassApp/tree/recordSensorReadings_1)
